### ISSUE TITLE
System.FormatException  [...] at System.Windows.Forms.Control.OnClick(EventArgs e)[...]This exception was originally thrown at this call stack: [External Code] CLR_WindowsForms::Form1::EnterOperator(System::Object^, System::EventArgs^) in Form1.h

### ISSUE THREAD

**Issue by MisterPython581** [MisterPython581/calculator#1]
An error occur when trying to do the following:

-  45 + 6
-  51 - 2
-  49
-  [User press on the "." button] 49.5 - **=>BUG<=**

Here is the error message (maybe too long):
*System.FormatException
  HResult=0x80131537
  Message=Le format de la chaîne d'entrée est incorrect.
  Source=mscorlib
  StackTrace:
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at CLR_WindowsForms.Form1.EnterOperator(Object sender, EventArgs e) in C:\Users\xxxxx\OneDrive\Documents\Visual Studio Projects\CalculatorTutorial\Calculator Tutorial\Calculator Tutorial\Form1.h:line 429
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at main() in C:\Users\xxxxx\OneDrive\Documents\Visual Studio Projects\CalculatorTutorial\Calculator Tutorial\Calculator Tutorial\CalculatorTutorial.cpp:line 18
  This exception was originally thrown at this call stack:
    [External Code]
    CLR_WindowsForms::Form1::EnterOperator(System::Object^, System::EventArgs^) in Form1.h
    [External Code]
    main(void) in CalculatorTutorial.cpp*

**Comment by MisterPython581** [comment]
I have just realized that the bug occurs because I have a French computer, and in France, the decimal number looks like 35,12, and in English it looks like 35.12.
